### PR TITLE
Add additional websocket message types

### PR DESCRIPTION
**Pull request by hjoelr**
The Coinbase API supports some additional websocket types. I'm adding them so they can be used natively in TypeScript.

### CODE REVIEW

**Comment by bennycode** [comment]
Hey @hjoelr, I am happy to add additional WebSocket types but we also need to have tests for the events when they occur.

**Comment by hjoelr** [comment]
@bennycode Okay. I've started to look at how to do that. I'm thinking I would add more `it(...)` calls under inside the `describe('subscribe'...)` section?

https://github.com/bennycode/coinbase-pro-node/blob/9f912cccadea0bcaa899a54f61751617120f5681/src/client/WebSocketClient.test.ts#L131-L261

**Comment by bennycode** [comment]
Hi @hjoelr, sorry for my late reply but I am currently on vacation (back to work next week). To add tests it's best to add more `it` blocks (one per message type test). If you change the `it` to `fit`, then only this test will be executed when running `yarn test`, which makes it pretty convenient to implement a new test. But don't forget to turn `fit` back into `it` when committing your final changes.

A full test run will also generate a "coverage/index.html" from where you can see which lines of code are covered by your test.

Here is a good example how to check for a specific message type:

https://github.com/bennycode/coinbase-pro-node/blob/9f912cccadea0bcaa899a54f61751617120f5681/src/client/WebSocketClient.test.ts#L176-L190

**Comment by bennycode** [comment]
Hi @hjoelr, I converted your PR to a draft because it's still in progress.

**Comment by bennycode** [comment]
Hey @hjoelr, can I help you with adding the missing tests? 🙂

**Comment by hjoelr** [comment]
@bennycode Um, good question 😊. I recently brought my branch back into sync with your version and was planning on figuring out how to do this. I just need to take the time to learn how to mock in Jasmine. I hope to eventually submit some additional PRs and need to learn how to do this. I wouldn't mind help, but I also don't want you to have to spend time to write tests I should be writing 🙄.

**Comment by hjoelr** [comment]
@bennycode I think this PR is ready for review and merge. Thanks for bearing with me on this one!

**Pull request merged**
